// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExportEvents(arg1:Array<main.CalendarEvent>):Promise<boolean|string>;
