// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {calendar} from '../models';

export function ExportEvents(arg1:Array<calendar.CalendarEvent>):Promise<string>;

export function ImportEvents(arg1:string):Promise<Array<calendar.CalendarEvent>>;
